Program portable over ten Scheme implementations.
This includes a local test runner, github action continuation
integration, dockerfile, and script to install on a Debian several
Scheme implementation, see `./venv scheme-live available`.

It demonstrate how to build a program that rely on a library that is
portable to several implementations. Here is what the repository looks
like:

% tree .
.
├── gerbil.pkg
├── live
│   ├── hello
│   │   └── body.scm
│   ├── hello.chez.sls
│   ├── hello.guile.sld
│   ├── hello.rkt
│   └── hello.sld

Where `body.scm` contains the code. The other files are importing the
required libraries, which may be r7rs, r6rs or something else entirely
depending on what each implementation decide to use as an entry point
into the library... It works with racket, see `hello.rkt`.

ref: https://github.com/lexi-lambda/racket-r7rs/issues/16

The directory ./scheme/ contains r7rs shims for chez, to make it
possible to run ./local/bin/hello-schemer and
./local/bin/hello-schemer-star.

Here is the content of `hello-schemer`:

```scheme
 #!/usr/bin/env -S scheme-live current run
 (import (scheme base))
 (import (scheme write))

 (display "Hello schemer!")
 (newline)
```

The bang in the first line is mostly useless. It was meant to make it
possible to run `hello-schemer` without going through the woops of
spelling the full:

  scheme-live fantastic run ./local/bin/hello-schemer

That dream was not completly realised, and calling the following:

  ./venv hello-schemer

Result in the following notice:

  Retry with something like:

    SCHEME_LIVE_CURRENT=fantastic hello-schemer

  Or:

    export SCHEME_LIVE_CURRENT=fantastic

  Then call the program.

That is to say, the user needs to set SCHEME_LIVE_CURRENT to something
that is supported.

At somepoint, we may get rid of the shell code, we are not there yet.

diff --git a/local/bin/scheme-live b/local/bin/scheme-live
--- a/local/bin/scheme-live
+++ b/local/bin/scheme-live
@@ -1,6 +1,48 @@
-#!/bin/sh
+#!/bin/bash
 
-set -xe
+# set -x # echo debug line by line
+set -e # Exit on error
 
-echo "Running checks..."
-echo "Arguments are:" $@
+# SHORT_DESCRIPTION="My command with various sub commands!"
+# HELP_MAIN="usage: $(basename "$0") <sub-commands> [options]
+#
+# sub-commands are made from alias, function, and executables in PATH."
+
+# scheme-live-chibi () {
+#     echo "chibi install in progress..."
+
+#     source $SCHEME_LIVE_PREFIX/src/shell-subcommand.sh
+# }
+
+alias scheme-live-chibi=scheme-live-chibi
+
+scheme-live-version () {
+    # Based on https://srfi.schemers.org/srfi-176/
+    echo '(command "scheme-live")'
+    echo '(website "https://github.com/scheme-live/live/")'
+    echo '(languages scheme r6rs r7rs)'
+    echo "(install-dir \"$SCHEME_LIVE_PREFIX\")"
+    echo '(scheme.id live)'
+    echo '(release "2021")'
+    echo '(release.name "Fantastic Moon")'
+    echo "(build.date \"$(date --iso=seconds)\")"
+    echo "(platform \"$(shtool platform --version --format '%sc (%ac) %st (%at) %sp (%ap)'\")\")"
+    echo "(commit \"$(git log --pretty="%H" -1)\")"
+    echo "(kernel-release \"$(uname --kernel-release)\")"
+    echo "(kernel-version \"$(uname --kernel-version)\")"
+}
+
+scheme-live-available () {
+    find $SCHEME_LIVE_PREFIX/bin/ -name "scheme-live-*" -exec sh -c 'basename {} | cut -d"-" -f3' \; | grep -v current | sort
+}
+
+scheme-live-check () {
+    find $SCHEME_LIVE_PREFIX/bin/ -name "scheme-live-*" -exec sh -c '{} check $@' \;
+}
+
+scheme-live-benchmark () {
+    FORMAT="command:%C\nwall-clock-time:%es\nmemory-average:%Kkb\ncpu:%P"
+    /usr/bin/time -f $FORMAT $@
+}
+
+source $SCHEME_LIVE_PREFIX/shell-subcommand.sh
